test: Creating test for shell script

diff --git a/private b/private
--- a/private
+++ b/private
@@ -7,7 +7,7 @@
 declare -A apps=(["python3"]="" ["python3-pip"]="" ["synaptic"]="" ["redshift"]="" ["shellcheck"]="" ["bleachbit"]=""
     ["vim"]="" ["vim-gtk"]="" ["vim-gtk3"]="" ["gparted"]="" ["build-essential"]="" ["make"]="" ["perl"]=""
     ["bluez"]="" ["blueman"]="" ["curl"]="" ["terminator"]="" ["fonts-firacode"]="" ["guvcview"]="" ["wget"]=""
-    ["gpg"]="" ["apt-transport-https"]="" ["git"]="")
+    ["gpg"]="" ["apt-transport-https"]="" ["git"]="" ["fonts-ubuntu"]="")
 
 declare -A vscode_plugs=(["ms-azuretools.vscode-docker"]="" ["streetsidesoftware.code-spell-checker"]="" ["idleberg.hopscotch"]="" ["ms-python.python"]=""
     ["timonwong.shellcheck"]="" ["redhat.vscode-yaml"]="" ["shardulm94.trailing-spaces"]="")
@@ -70,8 +70,13 @@ install_python_pkgs() {
 
 install_theme() {
 
-	if curl -s https://raw.githubusercontent.com/PeyamMaroufi/setup_linux/main/148144-prelude-dfr-0.5.tar.tar --create-dirs -o "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar; then
-		tar -xf "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar  &> /dev/null && rm "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar &> /dev/null
+	if [[ ! -d "$HOME"/.themes ]]; then
+		mkdir "$HOME"/.themes
+	fi
+
+	if curl -s https://raw.githubusercontent.com/PeyamMaroufi/setup_linux/main/148144-prelude-dfr-0.5.tar.tar -o "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar; then
+		tar -xf "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar -C "$HOME"/.themes/ &> /dev/null || { echo "Error: Could not extract tar file."; exit 1 }
+		rm "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar &> /dev/null
 		echo "Prelude theme is installed."
 	else
 		echo "Could not install Prelude theme."
diff --git a/test_script b/test_script
--- a/test_script
+++ b/test_script
@@ -1,3 +1,27 @@
-#! /bin/bash
-sleep $1;
-echo "Slept $1 seconds"
+#!/bin/bash
+# Test 1. Wrong argument
+./private -f || echo -e "Test: successfull."
+
+# Test 2. Install applications
+if ./private -a; then
+    if [[ -z which shellcheck ]]; then
+        echo "Error: Shellcheck could not be found"
+        exit 1
+    fi
+fi
+
+# Test 3. Install yocto libraries
+if ./private -y; then
+    if [[ -z which python2 ]]; then
+        echo "Error: Python2 not found."
+        exit 1
+    fi
+fi
+
+# Test 4. Install theme
+if ./private -t; then
+    if [[ ! -d "$HOME"/.themes ]]; then
+        echo "Didn't create the .themes folder"
+        exit 1
+    fi
+fi
