test: Creating test for shell script

diff --git a/private b/private
--- a/private
+++ b/private
@@ -75,7 +75,7 @@ install_theme() {
 	fi
 
 	if curl -s https://raw.githubusercontent.com/PeyamMaroufi/setup_linux/main/148144-prelude-dfr-0.5.tar.tar -o "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar; then
-		tar -xf "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar -C "$HOME"/.themes/ &> /dev/null || { echo "Error: Could not extract tar file."; exit 1 }
+		tar -xf "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar -C "$HOME"/.themes/ &> /dev/null || { echo "Error: Could not extract tar file."; exit 1; }
 		rm "$HOME"/.themes/148144-prelude-dfr-0.5.tar.tar &> /dev/null
 		echo "Prelude theme is installed."
 	else
