test: Creating test for shell script

diff --git a/test_script b/test_script
--- a/test_script
+++ b/test_script
@@ -1,27 +1,33 @@
 #!/bin/bash
 # Test 1. Wrong argument
-./private -f || echo -e "Test: successfull."
+./private -f || echo -e "Test 1: successful."
 
 # Test 2. Install applications
 if ./private -a; then
     if [[ -z which shellcheck ]]; then
-        echo "Error: Shellcheck could not be found"
+        echo "Test 2: Error - Shellcheck could not be found"
         exit 1
+    else
+        echo "Test 2: successful"
     fi
 fi
 
 # Test 3. Install yocto libraries
 if ./private -y; then
     if [[ -z which python2 ]]; then
-        echo "Error: Python2 not found."
+        echo "Test 3: Error - Python2 not found."
         exit 1
+    else
+        echo "Test 3: successful"
     fi
 fi
 
 # Test 4. Install theme
 if ./private -t; then
     if [[ ! -d "$HOME"/.themes ]]; then
-        echo "Didn't create the .themes folder"
+        echo "Test 4: Error - Didn't create the .themes folder"
         exit 1
+    else
+        echo "Test 4: successful"
     fi
 fi
