feat: Changing the test according to changes on new implementation.

diff --git a/test_script b/test_script
--- a/test_script
+++ b/test_script
@@ -1,42 +1,56 @@
 #!/bin/bash
 # Test 1. Wrong argument
-./private -f &> /dev/null || echo "Test 1: successful."
+./private f &> /dev/null || echo "Test 1: successful."
 
 # Test 2. Install applications
-if sudo ./private -a &> /dev/null; then
+if sudo ./private a &> /dev/null; then
     if [[ -z $(which shellcheck) ]]; then
-        echo "Test 2: Error - Shellcheck could not be found"
+        echo "Test 2: Error - Shellcheck could not be found."
         exit 1
     else
-        echo "Test 2: successful"
+        echo "Test 2: successful."
     fi
 else
-    echo "Test 2: Fail"
+    echo "Test 2: Fail."
     exit 1
 fi
 
 # Test 3. Install yocto libraries
-if sudo ./private -y &> /dev/null; then
+if sudo ./private y &> /dev/null; then
     if [[ -z $(which python2) ]]; then
         echo "Test 3: Error - Python2 not found."
         exit 1
     else
-        echo "Test 3: successful"
+        echo "Test 3: successful."
     fi
 else
-    echo "Test 3: Fail"
+    echo "Test 3: Fail."
     exit 1
 fi
 
 # Test 4. Install theme
-if ./private -t &> /dev/null; then
+if ./private t &> /dev/null; then
     if [[ ! -d "$HOME"/.themes ]]; then
-        echo "Test 4: Error - Didn't create the .themes folder"
+        echo "Test 4: Error - Didn't create the .themes folder."
         exit 1
     else
-        echo "Test 4: successful"
+        echo "Test 4: successful."
     fi
 else
-    echo "Test 4: Fail"
+    echo "Test 4: Fail."
     exit 1
 fi
+
+# Test 5. Install yocto libraries
+if sudo ./private d &> /dev/null; then
+    if [[ -z $(which docker) ]]; then
+        echo "Test 5: Error - Docker not found."
+        exit 1
+    else
+        echo "Test 5: successful."
+    fi
+else
+    echo "Test 5: Fail."
+    exit 1
+fi
+
